### ISSUE TITLE
[Feat] 실시간 재고 관리 서비스 구현

### ISSUE THREAD

**Issue by nayoonk928** [Reservation-Purchase-System/stock-service#1]
### Description
* 실시간 재고 관리 서비스

### TODO
- [x] product_service, purchase_service, payment_service와 내부 통신 구현
  - [x] product_service에 상품 재고 정보 요청
  - [x] purchase_service & payment_service 에서 결제 프로세스 진입 & 이탈시에 stock_service 호출
  - [x] product_service에서 초기 재고 수정 및 상품 삭제 시 stock_service 호출
- [x] 서비스 로직 구현
  - [x] redis 연결
  - [x] 현재 재고 계산 후 redis 업데이트
    - 현재 재고 = 상품 재고 정보 - 결제 진입한 주문
  - [x] 판매자가 초기 재고 변경시 현재 재고 다시 계산하여 업데이트
- [x] 테스트 코드
